services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: personalwebsite-5dbi.onrender.com
    healthCheckPath: /
    autoDeploy: true